[package]
name = "unchained"
version = "0.1.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Unchained Iteration"
repository = "https://github.com/sigmaSd/Unchained"
license = "MIT"

[dependencies]
